apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lnmp.fullname" . }}-config
  labels:
    app: {{ include "lnmp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
data:
  # nginx config
  nginx.conf: |-
  {{- .Files.Get "configfiles/files/nginx.conf" | indent 4 }}
  site.conf: |-
  {{- .Files.Get "configfiles/files/nginx-sites.conf" | indent 4 }}

  # phpfpm config
