apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnmp.fullname" . }}
  labels:
{{ include "lnmp.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # port: The port this service will be available on
    # targetPort: The container port the service will forward to
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "lnmp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
